# hix configuration file
# This file contains the configuration for the hix code generator

# The type of architecture (purely for documentation purposes)
architecture: onion

# Output root
output_root: C:\Users\joel\workplace\hix\sample\.hix\output

# Layers configuration
layers:
  - name: Domain
    path: C:\Users\joel\workplace\hix\sample\.hix\output\Domain
    description: Contains business logic and domain models
    templates:
      - template: C:\Users\joel\workplace\hix\sample\.hix\templates\domain\Archive.hix
        filename: {{model.name}}Archive.cs
        output_by: model

  - name: Application
    path: C:\Users\joel\workplace\hix\sample\.hix\output\Application
    description: Contains application services and use cases
    templates:
  - name: Infrastructure
    path: C:\Users\joel\workplace\hix\sample\.hix\output\Infrastructure
    description: Contains technical implementations
    templates:
  - name: Presentation
    path: C:\Users\joel\workplace\hix\sample\.hix\output\Presentation
    description: Contains UI and API controllers
    templates:
